#!/usr/bin/env python

import connexion
from .encoder import JSONEncoder
import os
import sys

if __name__ == '__main__':
    try:
        import googleclouddebugger
        googleclouddebugger.AttachDebugger()
    except ImportError:
        pass
    app = connexion.App(__name__, specification_dir='./swagger/')
    app.app.json_encoder = JSONEncoder
    app.add_api('swagger.yaml', arguments={'title': 'No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)'})
    app.run(port=sys.argv[1])
