# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.answers import Answers
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Question(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, question=None, answer=None):
        """
        Question - a model defined in Swagger

        :param question: The question of this Question.
        :type question: str
        :param answer: The answer of this Question.
        :type answer: Answers
        """
        self.swagger_types = {
            'question': str,
            'answer': Answers
        }

        self.attribute_map = {
            'question': 'question',
            'answer': 'answer'
        }

        self._question = question
        self._answer = answer

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Question of this Question.
        :rtype: Question
        """
        return deserialize_model(dikt, cls)

    @property
    def question(self):
        """
        Gets the question of this Question.

        :return: The question of this Question.
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question):
        """
        Sets the question of this Question.

        :param question: The question of this Question.
        :type question: str
        """

        self._question = question

    @property
    def answer(self):
        """
        Gets the answer of this Question.

        :return: The answer of this Question.
        :rtype: Answers
        """
        return self._answer

    @answer.setter
    def answer(self, answer):
        """
        Sets the answer of this Question.

        :param answer: The answer of this Question.
        :type answer: Answers
        """

        self._answer = answer

